name: Generate Weekend Blog Posts

on:
  schedule:
    # Saturdays and Sundays at 16:00 UTC
    - cron: '0 16 * * 6,0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate post via OpenRouter
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_REFERER: https://www.syntaxthreads.com
          OPENROUTER_TITLE: SyntaxThreadsCo
        run: node scripts/generate-post.js

      - name: Build to validate
        run: |
          npm ci
          npm run build

      - name: Commit and push changes
        run: |
          set -e
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(blog): auto-generate weekend post"
            git push
          else
            echo "No changes to commit"
          fi

